@startuml

component altair #lightskyblue
component appdirs #lightskyblue
component bitstamp #lightskyblue
component click #lightskyblue
component coloredlogs #lightskyblue
component dateutil #lightskyblue
component krakenex #lightskyblue
component numpy #lightskyblue
component pandas #lightskyblue
component requests #lightskyblue
component scipy #lightskyblue
component sqlalchemy #lightskyblue
component streamlit #lightskyblue
component yaml #lightskyblue

component commands
component configuration
component core
component datastorage
component evaluation
component feargreed
component historical
component marketplace
component marketplace
component myrequests
component paths
component streamlit_ui
component telegram
component triggers

click <-- commands
coloredlogs <-- commands
configuration <-- commands
datastorage <-- commands
historical <-- commands
marketplace <-- commands

dateutil <-- configuration
historical <-- configuration
marketplace <-- configuration
paths <-- configuration
telegram <-- configuration
triggers <-- configuration
yaml <-- configuration

core <-- datastorage
sqlalchemy <-- datastorage

core <-- evaluation
historical <-- evaluation
marketplace <-- evaluation
myrequests <-- evaluation
numpy <-- evaluation
pandas <-- evaluation
scipy <-- evaluation

myrequests <-- feargreed

core <-- historical
datastorage <-- historical
marketplace <-- historical
myrequests <-- historical

bitstamp <-- marketplace
core <-- marketplace
krakenex <-- marketplace

requests <-- myrequests

appdirs <-- paths

altair <-- streamlit_ui
evaluation <-- streamlit_ui
streamlit <-- streamlit_ui
numpy <-- streamlit_ui
pandas <-- streamlit_ui

myrequests <-- telegram
paths <-- telegram

datastorage <-- triggers
feargreed <-- triggers
historical <-- triggers
marketplace <-- triggers

@enduml
