@startuml
allowmixing

interface FearAndGreedIndex {
    get_value(datetime.datetime): int
}

class AlternateMeFearAndGreedIndex implements FearAndGreedIndex

class FearAndGreedException

AlternateMeFearAndGreedIndex -> FearAndGreedException

@enduml