@startuml

allowmixing

namespace telegram {
component requests

class TelegramConfig {
    token: str
    level: str
    chat_id: Optional[int]
}

class TelegramLogger extends python.logging.Handler {
format()
emit()
}

class TelegramBotException

class TelegramSender {
    queue_message()
    has_messages()
    wait_predicate()
    shutdown()
    watch_queue()
    get_chat_id()
    send_message()
}

TelegramConfig <-- TelegramSender

TelegramLogger -> TelegramSender
TelegramSender --> requests
TelegramSender -> TelegramBotException
paths.Paths <-- TelegramSender

}
@enduml