@startuml

allowmixing

namespace telegram {
component requests

class TelegramLogger extends python.logging.Handler {
format()
emit()
}

class TelegramBotException

class TelegramSender {
    queue_message()
    has_messages()
    wait_predicate()
    shutdown()
    watch_queue()
    get_chat_id()
    send_message()
}

TelegramLogger -> TelegramSender
TelegramSender --> requests
TelegramSender -> TelegramBotException

}
@enduml