#!/bin/bash

set -e
set -u
set -x

poetry run pytest
poetry run vigilant-crypto-snatch test-drive
git push
git push --tags
pushd docs/dev/graphs
make -j $(nproc)
popd
poetry run mkdocs gh-deploy
poetry build
poetry publish