#!/bin/bash

set -eux

# Publish source code.
git push
git push --tags

# Update documentation.
pushd docs/dev/graphs
make -j $(nproc)
popd
poetry run mkdocs gh-deploy

# Publish to PyPI.
poetry build
poetry publish
