#!/bin/bash

set -eux

# Bump the version according to conventional commits.
version="$(uv run cz bump --get-next)"
uv version "$version"

# Update the changelog.
today=$(date +%Y-%m-%d)
sed -i "s/## Unreleased/## Version $version — $today/" docs/changelog.md

# Commit and tag.
git ca -m "chore: bump version to $version"
git tag "v$version"

# Upload the code.
git push
git push --tags

# Publish the built project.
uv build
uv publish \
    --token "$PYPI_TOKEN_VIGILANT_CRYPTO_SNATCH" \
    "dist/vigilant_crypto_snatch-$version-py3-none-any.whl"

# Deploy documentation.
uv run mkdocs gh-deploy

# Create a GitHub release.
release_note_file="$(mktemp --suffix .md)"
uv run python3 extract-changelog.py docs/changelog.md "$version" > "$release_note_file"
gh release create "$version" -F "$release_note_file" -t "$version"
rm "$release_note_file"