@startuml

namespace core {

class AssetPair {
    coin: str
    fiat: str
}

class Price {
    timestamp: datetime.datetime
    last: float
    asset_pair: AssetPair
}

class Trade {
    timestamp: datetime.datetime
    trigger_name: str
    volume_coin: float
    volume_fiat: float
    asset_pair: AssetPair
}

AssetPair <-- Price
AssetPair <-- Trade

}

@enduml