@startuml

namespace core {

class Price {
    timestamp: datetime.datetime
    last: float
    coin: str
    fiat: str
}

class Trade {
    timestamp: datetime.datetime
    trigger_name: str
    volume_coin: float
    volume_fiat: float
    coin: str
    fiat: str
}

}

@enduml