@startuml
allowmixing


namespace feargreed {

interface FearAndGreedIndex {
    get_value(datetime.datetime): int
}

class AlternateMeFearAndGreedIndex implements FearAndGreedIndex

class FearAndGreedException

AlternateMeFearAndGreedIndex -> FearAndGreedException

myrequests.MyRequests <-- AlternateMeFearAndGreedIndex

}

@enduml