@startuml

!$standalone = 0

!include commands.puml
!include configuration.puml
!include core.puml
!include datastore.puml
!include evaluation.puml
!include feargreed.puml
!include historical.puml
!include marketplace.puml
!include notifications.puml
!include paths.puml
!include triggers.puml

@enduml